# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

export PERL_LOCAL_LIB_ROOT="$PERL_LOCAL_LIB_ROOT:/home/franz/perl5";
export PERL_MB_OPT="--install_base /home/franz/perl5";
export PERL_MM_OPT="INSTALL_BASE=/home/franz/perl5";
export PERL5LIB="/home/franz/perl5/lib/perl5:$PERL5LIB";
export PATH="/home/franz/perl6/bin:$PATH";

export PATH="~/bin:/usr/local/bin:$PATH"
PS1="\n\u@\h:\w \$(vcprompt -f '%b%m%u')\n> "

# Oracle enviroment setzen
. /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh

source  ~/bin/dotfiles/bash/bash_function
source  ~/bin/dotfiles/bash/bash_alias

alias homeshick="$HOME/.homesick/repos/homeshick/home/.homeshick"
